# Generated by Django 5.1.6 on 2025-03-27 18:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 27, 23, 51, 26, 221285), editable=False)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descriception', models.TextField()),
                ('image', models.ImageField(default='', upload_to='services/')),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 3, 27, 23, 51, 26, 219274), editable=False)),
                ('created_by', models.CharField(blank=True, default=0, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
