# Generated by Django 5.1.6 on 2025-03-28 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 12, 41, 2, 36415), editable=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 12, 41, 2, 36415), editable=False),
        ),
    ]
