# Generated by Django 5.1.6 on 2025-03-28 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_category_created_at_alter_services_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 12, 51, 17, 280764), editable=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 12, 51, 17, 280764), editable=False),
        ),
    ]
