# Generated by Django 5.1.6 on 2025-04-03 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_category_created_at_alter_services_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 11, 46, 17, 227870), editable=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 11, 46, 17, 227870), editable=False),
        ),
    ]
