# Generated by Django 5.1.6 on 2025-04-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_descriception_services_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
