# Generated by Django 5.1.6 on 2025-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herosection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='button',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
