# Generated by Django 5.1.6 on 2025-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_age', models.IntegerField()),
                ('pet_gender', models.CharField(max_length=100)),
                ('pet_color', models.CharField(max_length=100)),
                ('pet_personality', models.TextField()),
                ('pet_weight', models.FloatField()),
                ('pet_energylevel', models.CharField(max_length=100)),
                ('pet_disease', models.TextField()),
                ('pet_vaccinatedstatus', models.BooleanField()),
                ('pet_image', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
