# Generated by Django 5.1.6 on 2025-03-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_alter_adoption_pet_vaccinatedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
